In [48]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords

In [33]:
df = pd.read_csv("/content/sample_data/train (1).csv")

In [34]:
df

tweet_id airline_sentiment  airline_sentiment_confidence  \
0        Tr_tweet_1           neutral                        1.0000   
1        Tr_tweet_2          positive                        0.3486   
2        Tr_tweet_3           neutral                        0.6837   
3        Tr_tweet_4          negative                        1.0000   
4        Tr_tweet_5          negative                        1.0000   
...             ...               ...                           ...   
3334  Tr_tweet_3335          negative                        1.0000   
3335  Tr_tweet_3336          negative                        1.0000   
3336  Tr_tweet_3337          negative                        0.6678   
3337  Tr_tweet_3338          negative                        0.6667   
3338  Tr_tweet_3339          negative                        1.0000   

               negativereason  negativereason_confidence         airline  \
0                         NaN                        NaN  Virgin America   
1                         NaN                     0.0000  Virgin America   
2                         NaN                        NaN  Virgin America   
3                  Bad Flight                     0.7033  Virgin America   
4                  Can't Tell                     1.0000  Virgin America   
...                       ...                        ...             ...   
3334         Cancelled Flight                     1.0000          United   
3335              Late Flight                     1.0000          United   
3336  Flight Booking Problems                     0.3381          United   
3337             Lost Luggage                     0.6667          United   
3338                      NaN                        NaN             NaN   

               name  retweet_count  \
0           cairdin            0.0   
1          jnardino            0.0   
2        yvonnalynn            0.0   
3          jnardino            0.0   
4          jnardino            0.0   
...             ...            ...   
3334  GeorgeMcflyOG            0.0   
3335  GeorgeMcflyOG            0.0   
3336  GeorgeMcflyOG            0.0   
3337        Dayrean            0.0   
3338            NaN            NaN   

                                                   text  \
0                   @VirginAmerica What @dhepburn said.   
1     @VirginAmerica plus you've added commercials t...   
2     @VirginAmerica I didn't today... Must mean I n...   
3     @VirginAmerica it's really aggressive to blast...   
4     @VirginAmerica and it's a really big bad thing...   
...                                                 ...   
3334  @united idea: if u don't want us to be frustra...   
3335  @united I will be patient in my luxurious midd...   
3336  @united I will be patient as your agent explai...   
3337  @united please help trace my luggage which was...   
3338                                                NaN   

                  tweet_created tweet_location               user_timezone  
0     2015-02-24 11:35:52 -0800            NaN  Eastern Time (US & Canada)  
1     2015-02-24 11:15:59 -0800            NaN  Pacific Time (US & Canada)  
2     2015-02-24 11:15:48 -0800      Lets Play  Central Time (US & Canada)  
3     2015-02-24 11:15:36 -0800            NaN  Pacific Time (US & Canada)  
4     2015-02-24 11:14:45 -0800            NaN  Pacific Time (US & Canada)  
...                         ...            ...                         ...  
3334  2015-02-18 14:42:04 -0800            NJ   Eastern Time (US & Canada)  
3335  2015-02-18 14:40:23 -0800            NJ   Eastern Time (US & Canada)  
3336  2015-02-18 14:39:04 -0800            NJ   Eastern Time (US & Canada)  
3337  2015-02-18 14:37:52 -0800            NaN                         NaN  
3338                        NaN            NaN                         NaN  

[3339 rows x 12 columns]

In [36]:
df = df[["airline_sentiment","text"]]
df.head()

airline_sentiment                                               text
0           neutral                @VirginAmerica What @dhepburn said.
1          positive  @VirginAmerica plus you've added commercials t...
2           neutral  @VirginAmerica I didn't today... Must mean I n...
3          negative  @VirginAmerica it's really aggressive to blast...
4          negative  @VirginAmerica and it's a really big bad thing...

In [37]:
df.airline_sentiment.value_counts()

negative    2135
neutral      679
positive     525
Name: airline_sentiment, dtype: int64

In [38]:
df.replace(to_replace="positive",value="1",inplace=True)
df.replace(to_replace="negative",value="-1",inplace=True)
df.replace(to_replace="neutral",value="0",inplace=True)
df.head()

airline_sentiment                                               text
0                 0                @VirginAmerica What @dhepburn said.
1                 1  @VirginAmerica plus you've added commercials t...
2                 0  @VirginAmerica I didn't today... Must mean I n...
3                -1  @VirginAmerica it's really aggressive to blast...
4                -1  @VirginAmerica and it's a really big bad thing...

In [40]:
df.isnull().sum()

airline_sentiment    0
text                 1
dtype: int64

In [41]:
df.dropna(inplace=True)
df.head()

airline_sentiment                                               text
0                 0                @VirginAmerica What @dhepburn said.
1                 1  @VirginAmerica plus you've added commercials t...
2                 0  @VirginAmerica I didn't today... Must mean I n...
3                -1  @VirginAmerica it's really aggressive to blast...
4                -1  @VirginAmerica and it's a really big bad thing...

In [42]:
df.isnull().sum()

airline_sentiment    0
text                 0
dtype: int64

In [45]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [49]:
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['text'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [50]:
corpus[:5]

['virginamerica dhepburn said',
 'virginamerica plu ad commerci experi tacki',
 'virginamerica today must mean need take anoth trip',
 'virginamerica realli aggress blast obnoxi entertain guest face amp littl recours',
 'virginamerica realli big bad thing']

In [51]:
df["clean_text"] = corpus

In [52]:
df.head()

airline_sentiment                                               text  \
0                 0                @VirginAmerica What @dhepburn said.   
1                 1  @VirginAmerica plus you've added commercials t...   
2                 0  @VirginAmerica I didn't today... Must mean I n...   
3                -1  @VirginAmerica it's really aggressive to blast...   
4                -1  @VirginAmerica and it's a really big bad thing...   

                                          clean_text  
0                        virginamerica dhepburn said  
1         virginamerica plu ad commerci experi tacki  
2  virginamerica today must mean need take anoth ...  
3  virginamerica realli aggress blast obnoxi ente...  
4                 virginamerica realli big bad thing

In [54]:
import tensorflow as tf

In [58]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [57]:
voc_size = 5000
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[3470, 113, 4121],
 [3470, 4359, 959, 2967, 1997, 634],
 [3470, 2539, 735, 2549, 2048, 3994, 1079, 1914],
 [3470, 2103, 4284, 3791, 4301, 1511, 3414, 2453, 2097, 3312, 4390],
 [3470, 2103, 1291, 209, 2644],
 [3470, 500, 4589, 4350, 1767, 495, 682, 2103, 209, 2644, 2631, 4736],
 [3470, 1604, 2159, 2226, 3913, 2631, 231, 4368, 4610, 3366, 4687],
 [3470, 1223],
 [3470, 1833, 198, 2986, 215, 4375],
 [3470, 1563],
 [3470, 2030, 3380, 3569, 1091, 1859, 1914, 2594, 2097],
 [3470, 2938],
 [3470, 3684, 4103, 582, 948, 3877],
 [3470,
  1903,
  3750,
  1866,
  4288,
  1767,
  4979,
  3752,
  201,
  2497,
  2030,
  2644,
  2387,
  4512,
  4022],
 [2631, 3470],
 [3470, 2646, 4589, 1472, 2707, 1848, 30, 1418, 825, 2631],
 [3470, 3750, 4898, 4694, 4797, 3913, 3488, 495, 2780, 4324],
 [3470, 3616, 2786, 1955, 1240, 2834, 65],
 [3470, 3616, 2230, 4567, 4222, 4375, 4184],
 [3470, 1320, 1848, 1873],
 [3470,
  2911,
  4763,
  495,
  1292,
  495,
  4142,
  2911,
  2731,
  495,
  4687,
  825,
  1354,
  932

In [59]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[3470  113 4121 ...    0    0    0]
 [3470 4359  959 ...    0    0    0]
 [3470 2539  735 ...    0    0    0]
 ...
 [ 544 3452 3673 ...    0    0    0]
 [ 544 3452 4100 ...    0    0    0]
 [ 544 1418  601 ...    0    0    0]]


In [60]:
# Creating model
x = embedded_docs
y = df.airline_sentiment

In [61]:
x.shape

(3338, 20)

In [62]:
y.shape

(3338,)

In [65]:
import sklearn
from sklearn.model_selection import train_test_split

In [68]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [69]:
from sklearn.neighbors import KNeighborsClassifier
# Create KNN classifier
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [71]:
knn.score(x_test,y_test)

0.6457085828343313